[package]
name = "d3p1"
version = "0.1.0"
authors = ["Tim Rogers <rogers.timothy.john@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
